export const API_ENDPOINTS = {
    OTP_REQUEST: "/otp/request",
    OTP_VERIFY: "/otp/verify",
    USER_REGISTER: "/user/register",
    USER_LOGIN: "/user/login",
    USER_EXISTS: "/user/exists",
    COUNTRIES_MASTER_DATA: "/master/data/countries",
    PROJECT_COLORS: "/master/data/project/colors",
    PROJECT_CREATE: "/project/create",
    PROJECT_ALL: "/project/all",
    MEMBER_INVITE: "/member/invite",
    MEMBER_REQUEST: "/member/request",
    MEMBERS_ALL_BY_OWNER: "/members/all/by/owner",
    MEMBER_INVITE_CANCEL: "/member/invite/cancel",
    MEMBER_INVITE_REMOVE: "/member/invite/remove",
    MEMBER_CHANGE_NICKNAME: "/member/change/nickname",
    MEMBER_REMOVE: "/member/remove",
    PROJECT_TASK_TYPE_ADD: "/project-task-type/add",
    PROJECT_TASK_TYPE_UPDATE: "/project-task-type/update",
    PROJECT_TASK_TYPE_ALL: "/project-task-type/all",
    MASTER_DATA_USER_ROLES: "/master/data/user/roles",
    MASTER_DATA_USER_PERMISSIONS: "/master/data/user/permissions",
    MEMBER_ASSIGN_TO_PROJECT: "/member/assign/to/project",
    FILE_UPLOAD: "/file/upload",
    MEMBERS_ALL_BY_PROJECT: "/members/all/by/project",
    TASK_PLAN_CREATE: "/task/plan/create",
    TASK_UPDATE: "/task/update",
};
